// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwxqvcbrdzqqmsndhbjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3eHF2Y2JyZHpxcW1zbmRoYmpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjExNjksImV4cCI6MjA3MzkzNzE2OX0.BBmRiUXo-c_GuZgdoFyKvVBUP-gFfM-LfCJM5ygq5dI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});